server {
    listen 80 default_server;
    server_name _;

    location /rpc/ {
        gzip off;
        root /usr/lib/cgi-bin;
        fastcgi_pass unix:/run/fcgiwrap.socket;
        fastcgi_index index.cgi;
        include /etc/nginx/fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT   $document_root;
    }
}
